//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buy
    {
        public int id { get; set; }
        public int bookId { get; set; }
        public int pId { get; set; }
    
        public virtual Payment Payment { get; set; }
    }
}
